stages:
  - before
  - update
  - parse
  - commit
  - create_mr

variables:
  BRANCH_NAME: "update-submodules_$CI_COMMIT_SHA"

before_run:
  stage: before
  script:
    - apt update && apt install -y git curl jq
    - git config --global user.email "gitlab_admin_9dee57@example.com"
    - git config --global user.name "Administrator"
    - git checkout -b $BRANCH_NAME

update_submodules:
  stage: update
  script:
    - python3 update.py

parse:
  stage: parse
  script:
    - python3 parse.py

commit_changes:
  stage: commit
  script:
    - export COMMIT_TIME=$(git show -s --format=%ct $CI_COMMIT_SHA)
    - git add .
    - git commit -m "Обновление submodules $COMMIT_TIME"
    - git push --set-upstream origin $BRANCH_NAME

create_merge_request:
  stage: create_mr
  script:
    - export COMMIT_TIME=$(git show -s --format=%ct $CI_COMMIT_SHA)
    - |
      curl --request POST --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
        --data "source_branch=$BRANCH_NAME" \
        --data "target_branch=main" \
        --data "title=Обновление модулей $COMMIT_TIME" \
        "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/merge_requests"
  only:
    - main